[package]
name = "spacetimedb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "hello-wasm",
]

[profile.release]
opt-level = 's'
lto = true

[dependencies]
wasmer = "2.1.1"
wasm-bindgen = "0.2.79"
wasmer-middlewares = "2.1.1"
sha3 = "0.10.0"
hex-literal = "0.3.4"
hex = "0.4.3"
protobuf = { version = "2" }
prost = "0.6"

[dev-dependencies]
criterion = { version = "0.3", features = ["async", "async_tokio", "html_reports"] }
prost-build = { version = "0.6.1" }

[build-dependencies]
glob = "0.3.0"
prost-build = { version = "0.6.1" }