[package]
name = "spacetimedb-client-api"
version = "0.6.1"
edition = "2021"
license-file = "LICENSE"
description = "The HTTP API for SpacetimeDB"

[dependencies]
spacetimedb-core.workspace = true
tokio = { workspace = true, features = ["full"] }
lazy_static.workspace = true
spacetimedb-lib.workspace = true
log.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
anyhow = { workspace = true, features = ["backtrace"] }
regex.workspace = true
prometheus.workspace = true
email_address.workspace = true
tempdir.workspace = true
async-trait.workspace = true
chrono = { workspace = true, features = ["serde"]}
rand.workspace = true
axum = { workspace = true, features = ["headers", "ws", "tracing"] }
hyper.workspace = true
http.workspace = true
mime.workspace = true
tokio-stream = { workspace = true, features = ["sync"] }
futures.workspace = true
bytes.workspace = true
bytestring.workspace = true
tokio-tungstenite.workspace = true
itoa.workspace = true
