[package]
name = "spacetimedb-bench"
version = "0.6.1"
edition = "2021"
license-file = "LICENSE"
description = "Bench library/utility for SpacetimeDB"

[[bench]]
name = "db"
harness = false

[[bench]]
name = "modules"
harness = false

[lib]
bench = false

[dependencies]
spacetimedb-lib.workspace = true
spacetimedb-core.workspace = true
spacetimedb-standalone.workspace = true
spacetimedb-client-api.workspace = true
spacetimedb-testing.workspace = true

clap.workspace = true
rusqlite.workspace = true
criterion.workspace = true
tempdir.workspace = true
rand.workspace = true
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
byte-unit.workspace = true
