[package]
name = "spacetimedb-bench"
version = "0.6.1"
edition = "2021"
license-file = "LICENSE"
description = "Bench library/utility for SpacetimeDB"

[[bench]]
name = "db"
harness = false

[[bench]]
name = "modules"
harness = false

[lib]
bench = false

[dependencies]
spacetimedb-lib = { path = "../lib" }
spacetimedb-core = { path = "../core" }
spacetimedb-standalone = { path = "../standalone" }
spacetimedb-client-api = { path = "../client-api" }
spacetimedb-testing = { path = "../testing" }

anyhow.workspace = true
byte-unit.workspace = true
clap.workspace = true
criterion.workspace = true
rand.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
tempdir.workspace = true
tokio.workspace = true
