[package]
name = "sqltest"
version = "0.1.0"
edition = "2021"
description = "Sql integration test for SpaceTimeDb"

[dependencies]
spacetimedb-lib.workspace = true
spacetimedb-core.workspace = true
spacetimedb-sats.workspace = true

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap.workspace = true
console.workspace = true
fs-err.workspace = true
futures.workspace = true
glob.workspace = true
itertools.workspace = true
postgres-types.workspace = true
quick-junit.workspace = true
rusqlite.workspace = true
rust_decimal.workspace = true
sqllogictest-engines.workspace = true
sqllogictest.workspace = true
tempdir.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
