[package]
name = "spacetimedb-vm"
version = "0.6.1"
edition = "2021"
license-file = "LICENSE"
description = "A VM for SpacetimeDB"

[dependencies]
spacetimedb-sats.workspace = true
spacetimedb-lib.workspace = true

anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempdir.workspace = true
