[package]
name = "spacetimedb-vm"
version = "0.6.0"
edition = "2021"
license-file = "LICENSE"
description = "A VM for SpacetimeDB"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
spacetimedb-sats= { path = "../sats", version = "0.6.0" }
spacetimedb-lib = { path = "../lib", version = "0.6.0" }
thiserror = "1.0.37"
tracing = "0.1"

[dev-dependencies]
tempdir.workspace = true
