[package]
name = "spacetimedb-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spacetimedb-lib = { path = "../lib", version = "0.4.1" }
spacetimedb-core = { path = "../core", version = "0.4.1" }
spacetimedb-standalone = { path = "../standalone", version = "0.4.1" }
spacetimedb-client-api = { path = "../client-api", version = "0.4.1" }

tokio = { version = "1.25", features = ["full"]}
anyhow = "1.0"
serde_json = "1.0"
wasmbin = "0.6"
