[package]
name = "spacetimedb-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
spacetimedb-lib.workspace = true
spacetimedb-core.workspace = true
spacetimedb-standalone.workspace = true
spacetimedb-client-api.workspace = true

anyhow.workspace = true
serde_json.workspace = true
tokio.workspace = true
wasmbin.workspace = true

[dev-dependencies]
serial_test.workspace = true
