name: Contributor Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_membership:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install @octokit/rest @actions/core @actions/github

      - name: Verify author is contributor
        run: node .github/scripts/checkMembership.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

